dataset_params:
  dir: './datasets'
  batch_size: 512
  n_workers: 12

model_params:
  channels: 1
  image_height: 224
  image_width: 224
  patch_height: 16
  patch_width: 16
  emb_dim: 128
  n_heads: 8
  n_layers: 6
  hidden_dim: 256
  dropout: 0.1
  n_classes: 10

training_params:
  n_epochs: 100
  weight_decay: 0.1
  max_lr: 0.0004
  max_grad_norm: 1.0
  patience: 10
  label_smoothing: 0.1

eval_params:
  val_freq: 1