dataset_params:
  dir: './datasets'
  batch_size: 128
  n_workers: 12

model_params:
  channels: 3
  image_height: 224
  image_width: 224
  patch_height: 16
  patch_width: 16
  emb_dim: 768
  n_heads: 12
  n_layers: 12
  hidden_dim: 3072
  dropout: 0.2
  n_classes: 100

training_params:
  n_epochs: 150
  weight_decay: 0.1
  max_lr: 0.0004
  max_grad_norm: 1.0
  patience: 10
  label_smoothing: 0.1

eval_params:
  val_freq: 1